import React, { useState } from 'react';
import { ScreenSpec, DetectedIcon, DetectedAsset } from '../types';
import { Download, Check, ExternalLink, Image as ImageIcon, Sparkles, Search, Layers, RefreshCw } from 'lucide-react';
import { VECTOR_ICON_CATALOG, findClosestIcon } from '../data/vectorIcons';

interface AssetManagerProps {
  currentScreen: ScreenSpec;
  onUpdateScreenIcons?: (icons: DetectedIcon[]) => void;
}

export const AssetManager: React.FC<AssetManagerProps> = ({ currentScreen, onUpdateScreenIcons }) => {
  const [activeSubTab, setActiveSubTab] = useState<'icons' | 'images'>('icons');
  const [downloadedIconMap, setDownloadedIconMap] = useState<Record<string, boolean>>({});
  const [iconSearchQuery, setIconSearchQuery] = useState('');
  const [selectedIconForDetail, setSelectedIconForDetail] = useState<DetectedIcon | null>(null);

  // Download single icon as standalone .svg file
  const handleDownloadIcon = (iconName: string, iconKey: string) => {
    const match = findClosestIcon(iconKey || iconName);
    const svgContent = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="${match.icon.viewBox}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by Soul AI • Icon: ${match.icon.name} (${match.matchType}) -->
  ${match.icon.svgPath}
</svg>`;

    const blob = new Blob([svgContent], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${match.icon.key}.svg`;
    a.click();
    URL.revokeObjectURL(url);

    setDownloadedIconMap((prev) => ({ ...prev, [iconKey || iconName]: true }));
  };

  // Download all icons as a single SVG spritesheet / vector package
  const handleDownloadAllIcons = () => {
    const icons = currentScreen.icons || [];
    if (icons.length === 0) return;

    let bundleSvg = `<!-- Soul Icon Bundle for ${currentScreen.title} -->\n<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">\n`;
    icons.forEach((ic) => {
      const match = findClosestIcon(ic.iconKey || ic.name);
      bundleSvg += `  <symbol id="icon-${match.icon.key}" viewBox="${match.icon.viewBox}">\n    ${match.icon.svgPath}\n  </symbol>\n`;
    });
    bundleSvg += `</svg>`;

    const blob = new Blob([bundleSvg], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentScreen.id}-icons-sprite.svg`;
    a.click();
    URL.revokeObjectURL(url);

    const allMap: Record<string, boolean> = {};
    icons.forEach((ic) => {
      allMap[ic.iconKey || ic.name] = true;
    });
    setDownloadedIconMap((prev) => ({ ...prev, ...allMap }));
  };

  // Filtered icons
  const iconsList = currentScreen.icons || [];
  const filteredCatalogKeys = Object.keys(VECTOR_ICON_CATALOG).filter((k) => {
    const item = VECTOR_ICON_CATALOG[k];
    if (!iconSearchQuery) return true;
    const q = iconSearchQuery.toLowerCase();
    return item.name.toLowerCase().includes(q) || item.tags.some((t) => t.includes(q)) || item.category.toLowerCase().includes(q);
  });

  return (
    <div className="space-y-4">
      {/* Sub tabs */}
      <div className="flex items-center bg-[#0d131d] p-1 rounded-xl border border-[#1f2c3e]">
        <button
          onClick={() => setActiveSubTab('icons')}
          className={`flex-1 flex flex-col items-center justify-center gap-1.5 py-2 rounded-lg text-[11px] font-semibold transition-all ${
            activeSubTab === 'icons'
              ? 'bg-[#1a2638] text-sky-400 shadow-sm'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <Sparkles className="w-4 h-4" />
          <span className="text-center leading-tight">Icons & Vectors <br className="hidden 2xl:block" />({iconsList.length})</span>
        </button>
        <button
          onClick={() => setActiveSubTab('images')}
          className={`flex-1 flex flex-col items-center justify-center gap-1.5 py-2 rounded-lg text-[11px] font-semibold transition-all ${
            activeSubTab === 'images'
              ? 'bg-[#1a2638] text-emerald-400 shadow-sm'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <ImageIcon className="w-4 h-4" />
          <span className="text-center leading-tight">Images & Media <br className="hidden 2xl:block" />({(currentScreen.assets || []).length})</span>
        </button>
      </div>

      {activeSubTab === 'icons' && (
        <div className="space-y-3">
          {/* Header & Download All */}
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
              Extracted Vector Icons
            </span>
            {iconsList.length > 0 && (
              <button
                onClick={handleDownloadAllIcons}
                className="flex items-center gap-1 text-[11px] font-semibold text-sky-400 hover:text-sky-300 bg-sky-500/10 hover:bg-sky-500/20 border border-sky-500/30 px-2.5 py-1 rounded-lg transition-all"
              >
                <Download className="w-3 h-3" />
                <span>Download All SVGs</span>
              </button>
            )}
          </div>

          {/* Explanation note for match & download behavior */}
          <div className="p-2.5 bg-[#0f1724] border border-sky-500/20 rounded-xl text-[11px] text-slate-300 leading-relaxed flex items-start gap-2">
            <div className="w-4 h-4 rounded-full bg-sky-500/20 text-sky-400 flex items-center justify-center shrink-0 mt-0.5 font-bold text-[10px]">
              ✓
            </div>
            <div>
              <p className="font-medium text-slate-200">
                Exact & Closest Vector Matching Enabled
              </p>
              <p className="text-slate-400 mt-0.5">
                Icons detected from your screenshot are automatically converted to clean SVGs. If the exact icon is absent, the closest optical match is supplied and available for direct download.
              </p>
            </div>
          </div>

          {/* Extracted Icons List */}
          <div className="space-y-2">
            {iconsList.map((icon, idx) => {
              const match = findClosestIcon(icon.iconKey || icon.name);
              const isDownloaded = downloadedIconMap[icon.iconKey || icon.name] || icon.downloaded;

              return (
                <div
                  key={icon.id || idx}
                  className="p-2.5 bg-[#141b26] border border-[#202d3e] hover:border-slate-600 rounded-xl transition-all flex items-center justify-between gap-3 group"
                >
                  <div className="flex items-center gap-3">
                    {/* SVG preview render */}
                    <div className="w-9 h-9 rounded-lg bg-[#0c121a] border border-slate-700 flex items-center justify-center text-sky-400 shrink-0 shadow-inner group-hover:scale-105 transition-transform">
                      <svg
                        width="18"
                        height="18"
                        viewBox={match.icon.viewBox}
                        fill="none"
                        className="text-sky-300"
                        dangerouslySetInnerHTML={{ __html: match.icon.svgPath }}
                      />
                    </div>
                    <div>
                      <div className="flex items-center gap-1.5">
                        <h5 className="text-xs font-bold text-slate-100">{icon.name}</h5>
                        <span
                          className={`text-[9px] font-semibold uppercase px-1.5 py-0.2 rounded ${
                            match.matchType === 'exact'
                              ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                              : 'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                          }`}
                        >
                          {match.matchType === 'exact' ? 'Exact Match' : 'Closest Match'}
                        </span>
                      </div>
                      <p className="text-[10px] text-slate-400 font-mono">
                        Key: {match.icon.key} • Confidence {Math.round((icon.confidence || 0.95) * 100)}%
                      </p>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-1.5">
                    <button
                      onClick={() => handleDownloadIcon(icon.name, icon.iconKey)}
                      title="Download SVG file"
                      className={`p-1.5 rounded-lg border text-xs font-medium flex items-center gap-1 transition-all ${
                        isDownloaded
                          ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400'
                          : 'bg-[#1c2738] border-[#293a50] text-slate-300 hover:text-sky-400 hover:border-sky-500/50'
                      }`}
                    >
                      {isDownloaded ? (
                        <>
                          <Check className="w-3.5 h-3.5" />
                          <span className="text-[10px] hidden sm:inline">Saved</span>
                        </>
                      ) : (
                        <>
                          <Download className="w-3.5 h-3.5" />
                          <span className="text-[10px] hidden sm:inline">SVG</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Quick Icon Search & Discover */}
          <div className="pt-2">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block mb-2">
              Browse Full Vector Library (Instant Download)
            </span>
            <div className="relative mb-2">
              <Search className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search closest icons (e.g. arrow, bell, user, flame)..."
                value={iconSearchQuery}
                onChange={(e) => setIconSearchQuery(e.target.value)}
                className="w-full bg-[#0d131d] border border-[#202d3e] focus:border-sky-500 rounded-xl pl-8 pr-3 py-1.5 text-xs text-slate-200 placeholder-slate-500 outline-none transition-all"
              />
            </div>

            <div className="grid grid-cols-2 gap-1.5 max-h-48 overflow-y-auto pr-1">
              {filteredCatalogKeys.slice(0, 12).map((key) => {
                const def = VECTOR_ICON_CATALOG[key];
                return (
                  <button
                    key={key}
                    onClick={() => handleDownloadIcon(def.name, def.key)}
                    className="p-2 bg-[#121924] hover:bg-[#182333] border border-[#1e2a3c] hover:border-sky-500/40 rounded-lg flex items-center justify-between text-left transition-all group"
                  >
                    <div className="flex items-center gap-2 overflow-hidden">
                      <div className="w-6 h-6 rounded bg-[#0b1017] flex items-center justify-center text-sky-400 shrink-0">
                        <svg
                          width="14"
                          height="14"
                          viewBox={def.viewBox}
                          fill="none"
                          dangerouslySetInnerHTML={{ __html: def.svgPath }}
                        />
                      </div>
                      <span className="text-[11px] text-slate-300 font-medium truncate group-hover:text-sky-300">
                        {def.name}
                      </span>
                    </div>
                    <Download className="w-3 h-3 text-slate-500 group-hover:text-sky-400 shrink-0" />
                  </button>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {activeSubTab === 'images' && (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
              Discovered Stock Photography
            </span>
          </div>

          <div className="space-y-2">
            {(currentScreen.assets || []).map((asset, idx) => (
              <div
                key={asset.id || idx}
                className="p-2.5 bg-[#141b26] border border-[#202d3e] rounded-xl space-y-2.5"
              >
                <div className="flex items-start gap-2.5">
                  <img
                    src={asset.thumbnailUrl || asset.matchedUrl}
                    alt={asset.name}
                    className="w-14 h-14 rounded-lg object-cover border border-slate-700 shrink-0"
                  />
                  <div className="overflow-hidden flex-1">
                    <h4 className="text-xs font-bold text-slate-100 truncate">{asset.name}</h4>
                    <span className="text-[10px] text-emerald-400 font-semibold block mt-0.5">
                      {asset.license}
                    </span>
                    <p className="text-[10px] text-slate-400 truncate">Source: {asset.source} • By {asset.author}</p>
                  </div>
                </div>

                <div className="flex items-center justify-between pt-1 border-t border-[#1c2738]">
                  <span className="text-[10px] text-slate-500 font-mono">
                    Keywords: {asset.searchKeywords || 'lifestyle, portrait'}
                  </span>
                  <a
                    href={asset.matchedUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-1 text-[11px] font-semibold text-sky-400 hover:text-sky-300 bg-sky-500/10 px-2 py-1 rounded-md"
                  >
                    <Download className="w-3 h-3" />
                    <span>Download Original</span>
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
